In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns

In [2]:
file_path='train.csv'
df=pd.read_csv(file_path)
df.head()

,Product_Identifier,Supermarket_Identifier,Product_Supermarket_Identifier,Product_Weight,Product_Fat_Content,Product_Shelf_Visibility,Product_Type,Product_Price,Supermarket_Opening_Year,Supermarket _Size,Supermarket_Location_Type,Supermarket_Type,Product_Supermarket_Sales
0,DRB24,CHUKWUDI017,DRB24_CHUKWUDI017,8.785,Low Fat,0.020694,Soft Drinks,382.91,2014,NaN,Cluster 2,Supermarket Type1,4633.97
1,FDR31,CHUKWUDI019,FDR31_CHUKWUDI019,NaN,Normal Fat,0.086078,Fruits and Vegetables,359.53,1992,Small,Cluster 1,Grocery Store,729.05
2,FDP16,CHUKWUDI017,FDP16_CHUKWUDI017,18.600,Low Fat,0.039517,Frozen Foods,609.20,2014,NaN,Cluster 2,Supermarket Type1,14740.81
3,FDY16,CHUKWUDI027,FDY16_CHUKWUDI027,NaN,Normal Fat,0.091780,Frozen Foods,456.32,1992,Medium,Cluster 3,Supermarket Type3,16137.33
4,FDY48,CHUKWUDI046,FDY48_CHUKWUDI046,14.000,Low Fat,0.023735,Baking Goods,258.08,2004,Small,Cluster 1,Supermarket Type1,4613.99

In [3]:
path='test.csv'
df2=pd.read_csv(path)
df2.head()
# df2.isnull().sum()

,Product_Identifier,Supermarket_Identifier,Product_Supermarket_Identifier,Product_Weight,Product_Fat_Content,Product_Shelf_Visibility,Product_Type,Product_Price,Supermarket_Opening_Year,Supermarket _Size,Supermarket_Location_Type,Supermarket_Type
0,FDC15,CHUKWUDI049,FDC15_CHUKWUDI049,18.100,Low Fat,0.178246,Dairy,395.32,2006,Medium,Cluster 1,Supermarket Type1
1,NCY06,CHUKWUDI018,NCY06_CHUKWUDI018,15.250,Low Fat,0.061434,Household,327.49,2016,Medium,Cluster 3,Supermarket Type2
2,DRB24,CHUKWUDI035,DRB24_CHUKWUDI035,8.785,Low Fat,0.020573,Soft Drinks,391.16,2011,Small,Cluster 2,Supermarket Type1
3,NCG54,CHUKWUDI018,NCG54_CHUKWUDI018,12.100,Low Fat,0.080131,Household,427.28,2016,Medium,Cluster 3,Supermarket Type2
4,NCA42,CHUKWUDI017,NCA42_CHUKWUDI017,6.965,Low Fat,0.028710,Household,395.40,2014,NaN,Cluster 2,Supermarket Type1

In [4]:
df.describe(include='all')

,Product_Identifier,Supermarket_Identifier,Product_Supermarket_Identifier,Product_Weight,Product_Fat_Content,Product_Shelf_Visibility,Product_Type,Product_Price,Supermarket_Opening_Year,Supermarket _Size,Supermarket_Location_Type,Supermarket_Type,Product_Supermarket_Sales
count,3742,3742,3742,3141.000000,3742,3742.000000,3742,3742.000000,3742.000000,2616,3742,3742,3742.000000
unique,1367,10,3742,NaN,3,NaN,16,NaN,NaN,3,3,4,NaN
top,NCL31,CHUKWUDI017,FDZ43_CHUKWUDI027,NaN,Low Fat,NaN,Snack Foods,NaN,NaN,Medium,Cluster 3,Supermarket Type1,NaN
freq,9,461,1,NaN,2272,NaN,563,NaN,NaN,1155,1438,2495,NaN
mean,NaN,NaN,NaN,12.870640,NaN,0.066613,NaN,391.815315,2004.778461,NaN,NaN,NaN,6103.735353
std,NaN,NaN,NaN,4.730432,NaN,0.052951,NaN,120.204222,8.276712,NaN,NaN,NaN,4456.169125
min,NaN,NaN,NaN,4.555000,NaN,0.000000,NaN,78.730000,1992.000000,NaN,NaN,NaN,83.230000
25%,NaN,NaN,NaN,8.630000,NaN,0.026971,NaN,308.392500,1994.000000,NaN,NaN,NaN,2728.120000
50%,NaN,NaN,NaN,12.600000,NaN,0.053517,NaN,393.910000,2006.000000,NaN,NaN,NaN,5374.675000
75%,NaN,NaN,NaN,17.100000,NaN,0.095094,NaN,466.480000,2011.000000,NaN,NaN,NaN,8524.737500
max,NaN,NaN,NaN,21.350000,NaN,0.328391,NaN,667.220000,2016.000000,NaN,NaN,NaN,28612.760000

# Treating Missing Values

In [5]:
df["Supermarket _Size"].replace(np.nan, "Medium", inplace=True)
df2["Supermarket _Size"].replace(np.nan, "Medium", inplace=True)
df.Product_Weight=df.sort_values(['Product_Identifier','Product_Weight']).Product_Weight.ffill( )
df2.Product_Weight=df.sort_values(['Product_Identifier','Product_Weight']).Product_Weight.ffill( )

In [6]:
grouped_2=df[['Supermarket_Type', 'Product_Supermarket_Sales']]
grpd_2=grouped_2.groupby(['Supermarket_Type'],as_index=False).mean()
grpd_2.sort_values('Product_Supermarket_Sales',ascending=False)

    Supermarket_Type  Product_Supermarket_Sales
3  Supermarket Type3               12541.373382
1  Supermarket Type1                6434.596537
2  Supermarket Type2                5588.015335
0      Grocery Store                 821.426611

# Encoding

In [7]:
# df['Supermarket_Type'].replace('Supermarket Type3',4, inplace=True)
# df['Supermarket_Type'].replace('Supermarket Type1',3, inplace=True)
# df['Supermarket_Type'].replace('Supermarket Type2',2, inplace=True)
# df['Supermarket_Type'].replace('Grocery Store',1, inplace=True)
# # df[['Supermarket_Type']]

# df2['Supermarket_Type'].replace('Supermarket Type3',4, inplace=True)
# df2['Supermarket_Type'].replace('Supermarket Type1',3, inplace=True)
# df2['Supermarket_Type'].replace('Supermarket Type2',2, inplace=True)
# df2['Supermarket_Type'].replace('Grocery Store',1, inplace=True)
# # df2[['Supermarket_Type']]

In [8]:
# sns.boxplot(x="Supermarket_Type", y="Product_Supermarket_Sales", data=df)

In [9]:
# grpd_2=grouped_2.groupby(['Supermarket_Type'],as_index=False)
# f_val, p_val = stats.f_oneway(grpd_2.get_group('Supermarket Type1')['Product_Supermarket_Sales'], grpd_2.get_group('Supermarket Type2')['Product_Supermarket_Sales'], grpd_2.get_group('Supermarket Type3')['Product_Supermarket_Sales'], grpd_2.get_group('Grocery Store')['Product_Supermarket_Sales'])  
# print( "ANOVA results: F=", f_val, ", P =", p_val)

In [10]:
# df['Supermarket_Type'].value_counts()

# Supermarket_Location_Type analysis

In [11]:
# grouped_3=df[['Supermarket_Location_Type', 'Product_Supermarket_Sales']]
# grpd_3=grouped_3.groupby(['Supermarket_Location_Type'],as_index=False).mean()
# grpd_3

# Encoding

In [12]:
# df['Supermarket_Location_Type'].replace('Cluster 2',3, inplace=True)
# df['Supermarket_Location_Type'].replace('Cluster 3',2, inplace=True)
# df['Supermarket_Location_Type'].replace('Cluster 1',1, inplace=True)
# # df['Supermarket_Location_Type'].value_counts()

# df2['Supermarket_Location_Type'].replace('Cluster 2',3, inplace=True)
# df2['Supermarket_Location_Type'].replace('Cluster 3',2, inplace=True)
# df2['Supermarket_Location_Type'].replace('Cluster 1',1, inplace=True)
# # df2['Supermarket_Location_Type'].value_counts()

In [13]:
# df['Supermarket_Location_Type'].value_counts()

In [14]:
# sns.boxplot(x="Supermarket_Location_Type", y="Product_Supermarket_Sales", data=df)

In [15]:
# grpd_3=grouped_3.groupby(['Supermarket_Location_Type'],as_index=False)
# f_val, p_val = stats.f_oneway(grpd_3.get_group('Cluster 1')['Product_Supermarket_Sales'], grpd_3.get_group('Cluster 2')['Product_Supermarket_Sales'], grpd_3.get_group('Cluster 3')['Product_Supermarket_Sales'])  
# print( "ANOVA results: F=", f_val, ", P =", p_val)

# Product_Fat_Content analysis

In [16]:
# df['Product_Fat_Content'].value_counts()

In [17]:
# grouped_4=df[['Product_Fat_Content', 'Product_Supermarket_Sales']]
# grpd_4=grouped_4.groupby(['Product_Fat_Content'],as_index=False).mean()
# grpd_4

# Encoding

In [18]:
# df['Product_Fat_Content'].replace('Low Fat',3, inplace=True)
# df['Product_Fat_Content'].replace('Normal Fat',2, inplace=True)
# df['Product_Fat_Content'].replace('Ultra Low fat',1, inplace=True)
# # df['Product_Fat_Content'].value_counts()
# df2['Product_Fat_Content'].replace('Low Fat',3, inplace=True)
# df2['Product_Fat_Content'].replace('Normal Fat',2, inplace=True)
# df2['Product_Fat_Content'].replace('Ultra Low fat',1, inplace=True)
# # df2['Product_Fat_Content'].value_counts()

In [19]:
# sns.boxplot(x='Product_Fat_Content', y='Product_Supermarket_Sales', data=df)

In [20]:
# grpd_4=grouped_4.groupby(['Product_Fat_Content'],as_index=False)
# f_val, p_val = stats.f_oneway(grpd_4.get_group('Low Fat')['Product_Supermarket_Sales'], grpd_4.get_group('Normal Fat')['Product_Supermarket_Sales'], grpd_4.get_group('Ultra Low fat')['Product_Supermarket_Sales'])  
# print( "ANOVA results: F=", f_val, ", P =", p_val)

In [21]:
df.head()

,Product_Identifier,Supermarket_Identifier,Product_Supermarket_Identifier,Product_Weight,Product_Fat_Content,Product_Shelf_Visibility,Product_Type,Product_Price,Supermarket_Opening_Year,Supermarket _Size,Supermarket_Location_Type,Supermarket_Type,Product_Supermarket_Sales
0,DRB24,CHUKWUDI017,DRB24_CHUKWUDI017,8.785,Low Fat,0.020694,Soft Drinks,382.91,2014,Medium,Cluster 2,Supermarket Type1,4633.97
1,FDR31,CHUKWUDI019,FDR31_CHUKWUDI019,6.460,Normal Fat,0.086078,Fruits and Vegetables,359.53,1992,Small,Cluster 1,Grocery Store,729.05
2,FDP16,CHUKWUDI017,FDP16_CHUKWUDI017,18.600,Low Fat,0.039517,Frozen Foods,609.20,2014,Medium,Cluster 2,Supermarket Type1,14740.81
3,FDY16,CHUKWUDI027,FDY16_CHUKWUDI027,18.350,Normal Fat,0.091780,Frozen Foods,456.32,1992,Medium,Cluster 3,Supermarket Type3,16137.33
4,FDY48,CHUKWUDI046,FDY48_CHUKWUDI046,14.000,Low Fat,0.023735,Baking Goods,258.08,2004,Small,Cluster 1,Supermarket Type1,4613.99

In [22]:
df2.head()

,Product_Identifier,Supermarket_Identifier,Product_Supermarket_Identifier,Product_Weight,Product_Fat_Content,Product_Shelf_Visibility,Product_Type,Product_Price,Supermarket_Opening_Year,Supermarket _Size,Supermarket_Location_Type,Supermarket_Type
0,FDC15,CHUKWUDI049,FDC15_CHUKWUDI049,8.785,Low Fat,0.178246,Dairy,395.32,2006,Medium,Cluster 1,Supermarket Type1
1,NCY06,CHUKWUDI018,NCY06_CHUKWUDI018,6.460,Low Fat,0.061434,Household,327.49,2016,Medium,Cluster 3,Supermarket Type2
2,DRB24,CHUKWUDI035,DRB24_CHUKWUDI035,18.600,Low Fat,0.020573,Soft Drinks,391.16,2011,Small,Cluster 2,Supermarket Type1
3,NCG54,CHUKWUDI018,NCG54_CHUKWUDI018,18.350,Low Fat,0.080131,Household,427.28,2016,Medium,Cluster 3,Supermarket Type2
4,NCA42,CHUKWUDI017,NCA42_CHUKWUDI017,14.000,Low Fat,0.028710,Household,395.40,2014,Medium,Cluster 2,Supermarket Type1

# Assigning Dependent and Independent Variables

In [74]:
X=df.drop(['Product_Identifier','Product_Supermarket_Identifier','Product_Weight','Product_Supermarket_Sales'], axis=1)

In [24]:
# X=df.drop(['Product_Identifier','Product_Supermarket_Identifier','Product_Type','Product_Weight',
#            'Supermarket_Opening_Year','Product_Supermarket_Sales'], axis=1)

In [25]:
""'Product_Fat_Content',

('Product_Fat_Content',)

In [75]:
X.head()

,Supermarket_Identifier,Product_Fat_Content,Product_Shelf_Visibility,Product_Type,Product_Price,Supermarket_Opening_Year,Supermarket _Size,Supermarket_Location_Type,Supermarket_Type
0,CHUKWUDI017,Low Fat,0.020694,Soft Drinks,382.91,2014,Medium,Cluster 2,Supermarket Type1
1,CHUKWUDI019,Normal Fat,0.086078,Fruits and Vegetables,359.53,1992,Small,Cluster 1,Grocery Store
2,CHUKWUDI017,Low Fat,0.039517,Frozen Foods,609.20,2014,Medium,Cluster 2,Supermarket Type1
3,CHUKWUDI027,Normal Fat,0.091780,Frozen Foods,456.32,1992,Medium,Cluster 3,Supermarket Type3
4,CHUKWUDI046,Low Fat,0.023735,Baking Goods,258.08,2004,Small,Cluster 1,Supermarket Type1

In [76]:
y=df.Product_Supermarket_Sales
y.head()

0     4633.97
1      729.05
2    14740.81
3    16137.33
4     4613.99
Name: Product_Supermarket_Sales, dtype: float64

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# catBOOST

In [49]:
from catboost import CatBoostRegressor

In [103]:
ctb = CatBoostRegressor(cat_features =[0,1,3,6,7,8],depth=5, learning_rate=0.02, n_estimators=270)
# ctb = CatBoostRegressor(cat_features =[0,1,3,6,7,8],learning_rate=0.08, n_estimators=127)
# ctb = CatBoostRegressor(cat_features =[0,1,3,6,7,8],depth=5, learning_rate=0.07, n_estimators=150)
# ctb = CatBoostRegressor(cat_features =[0,1,3,6,7,8],learning_rate=0.02, n_estimators=270)
ctb.fit(X_train,y_train)

0:	learn: 4357.9321779	total: 33.1ms	remaining: 8.91s
1:	learn: 4316.6692055	total: 52.6ms	remaining: 7.05s
2:	learn: 4273.6452128	total: 85.3ms	remaining: 7.59s
3:	learn: 4234.2603186	total: 122ms	remaining: 8.1s
4:	learn: 4193.0529640	total: 144ms	remaining: 7.61s
5:	learn: 4152.6552220	total: 165ms	remaining: 7.28s
6:	learn: 4114.0841370	total: 187ms	remaining: 7.01s
7:	learn: 4077.0924429	total: 209ms	remaining: 6.85s
8:	learn: 4041.3560346	total: 231ms	remaining: 6.69s
9:	learn: 4007.3441167	total: 271ms	remaining: 7.03s
10:	learn: 3974.5145893	total: 301ms	remaining: 7.09s
11:	learn: 3942.9185375	total: 334ms	remaining: 7.19s
12:	learn: 3912.3495153	total: 353ms	remaining: 6.99s
13:	learn: 3882.7846044	total: 379ms	remaining: 6.93s
14:	learn: 3851.3333852	total: 434ms	remaining: 7.38s
15:	learn: 3822.2972419	total: 471ms	remaining: 7.48s
16:	learn: 3794.0256046	total: 519ms	remaining: 7.72s
17:	learn: 3767.0756750	total: 554ms	remaining: 7.76s
18:	learn: 3741.6564303	total: 575ms	remaining: 7.6s
19:	learn: 3715.0659780	total: 597ms	remaining: 7.46s
20:	learn: 3691.1901328	total: 631ms	remaining: 7.48s
21:	learn: 3665.7197765	total: 663ms	remaining: 7.47s
22:	learn: 3642.0863732	total: 700ms	remaining: 7.51s
23:	learn: 3619.4280437	total: 727ms	remaining: 7.45s
24:	learn: 3598.8078164	total: 754ms	remaining: 7.39s
25:	learn: 3577.4922907	total: 793ms	remaining: 7.44s
26:	learn: 3557.1471657	total: 818ms	remaining: 7.36s
27:	learn: 3537.3323509	total: 874ms	remaining: 7.55s
28:	learn: 3518.4900320	total: 904ms	remaining: 7.51s
29:	learn: 3499.4438997	total: 969ms	remaining: 7.75s
30:	learn: 3480.9909009	total: 992ms	remaining: 7.65s
31:	learn: 3463.4156058	total: 1.03s	remaining: 7.66s
32:	learn: 3444.9678387	total: 1.07s	remaining: 7.7s
33:	learn: 3427.2115559	total: 1.1s	remaining: 7.65s
34:	learn: 3409.6939089	total: 1.14s	remaining: 7.64s
35:	learn: 3394.8544680	total: 1.16s	remaining: 7.54s
36:	learn: 3379.7654863	total: 1.19s	remaining: 7.46s
37:	learn: 3365.0059540	total: 1.22s	remaining: 7.44s
38:	learn: 3352.3046156	total: 1.25s	remaining: 7.43s
39:	learn: 3338.1449260	total: 1.29s	remaining: 7.42s
40:	learn: 3324.9108034	total: 1.32s	remaining: 7.35s
41:	learn: 3313.7136533	total: 1.35s	remaining: 7.31s
42:	learn: 3303.0776163	total: 1.36s	remaining: 7.18s
43:	learn: 3290.5240362	total: 1.38s	remaining: 7.1s
44:	learn: 3278.3417244	total: 1.41s	remaining: 7.06s
45:	learn: 3265.3534837	total: 1.45s	remaining: 7.08s
46:	learn: 3254.3591828	total: 1.48s	remaining: 7.02s
47:	learn: 3244.0236937	total: 1.5s	remaining: 6.93s
48:	learn: 3232.2142145	total: 1.51s	remaining: 6.84s
49:	learn: 3222.2883062	total: 1.53s	remaining: 6.75s
50:	learn: 3212.9239485	total: 1.56s	remaining: 6.68s
51:	learn: 3204.3547596	total: 1.6s	remaining: 6.71s
52:	learn: 3195.2598184	total: 1.62s	remaining: 6.65s
53:	learn: 3186.4867501	total: 1.66s	remaining: 6.63s
54:	learn: 3177.7466256	total: 1.69s	remaining: 6.59s
55:	learn: 3167.4968737	total: 1.71s	remaining: 6.53s
56:	learn: 3159.7175934	total: 1.73s	remaining: 6.48s
57:	learn: 3151.1134366	total: 1.8s	remaining: 6.58s
58:	learn: 3142.5596207	total: 1.83s	remaining: 6.55s
59:	learn: 3134.0754757	total: 1.85s	remaining: 6.46s
60:	learn: 3126.8686740	total: 1.86s	remaining: 6.39s
61:	learn: 3119.7680251	total: 1.89s	remaining: 6.35s
62:	learn: 3115.5342028	total: 1.9s	remaining: 6.24s
63:	learn: 3108.1846652	total: 1.92s	remaining: 6.18s
64:	learn: 3101.4793917	total: 2s	remaining: 6.31s
65:	learn: 3095.0411369	total: 2.04s	remaining: 6.29s
66:	learn: 3088.9541053	total: 2.07s	remaining: 6.28s
67:	learn: 3083.2493640	total: 2.1s	remaining: 6.23s
68:	learn: 3076.7794388	total: 2.15s	remaining: 6.26s
69:	learn: 3070.9911381	total: 2.18s	remaining: 6.22s
70:	learn: 3065.5935408	total: 2.21s	remaining: 6.18s
71:	learn: 3059.7791594	total: 2.23s	remaining: 6.14s
72:	learn: 3054.9118532	total: 2.26s	remaining: 6.11s
73:	learn: 3049.1435702	total: 2.3s	remaining: 6.1s
74:	learn: 3045.1335107	total: 2.36s	remaining: 6.14s
75:	learn: 3041.7593414	total: 2.39s	remaining: 6.1s
76:	learn: 3039.7450267	total: 2.4s	remaining: 6.01s
77:	learn: 3034.5374945	total: 2.42s	remaining: 5.97s
78:	learn: 3030.4250665	total: 2.44s	remaining: 5.9s
79:	learn: 3025.3602536	total: 2.47s	remaining: 5.87s
80:	learn: 3022.3341472	total: 2.49s	remaining: 5.82s
81:	learn: 3019.0559089	total: 2.56s	remaining: 5.87s
82:	learn: 3014.1980536	total: 2.59s	remaining: 5.84s
83:	learn: 3010.6178348	total: 2.61s	remaining: 5.78s
84:	learn: 3007.6195719	total: 2.65s	remaining: 5.77s
85:	learn: 3003.5550497	total: 2.68s	remaining: 5.73s
86:	learn: 3000.0364109	total: 2.73s	remaining: 5.75s
87:	learn: 2995.7921636	total: 2.77s	remaining: 5.72s
88:	learn: 2991.6994552	total: 2.8s	remaining: 5.69s
89:	learn: 2989.6472674	total: 2.82s	remaining: 5.64s
90:	learn: 2986.7460689	total: 2.84s	remaining: 5.58s
91:	learn: 2984.0606844	total: 2.87s	remaining: 5.55s
92:	learn: 2980.5509502	total: 2.89s	remaining: 5.5s
93:	learn: 2977.9932063	total: 2.91s	remaining: 5.45s
94:	learn: 2974.9824186	total: 2.94s	remaining: 5.41s
95:	learn: 2971.8876192	total: 2.98s	remaining: 5.4s
96:	learn: 2969.6284041	total: 3.01s	remaining: 5.37s
97:	learn: 2967.5014338	total: 3.06s	remaining: 5.38s
98:	learn: 2965.2888307	total: 3.1s	remaining: 5.35s
99:	learn: 2962.7701745	total: 3.12s	remaining: 5.31s
100:	learn: 2959.7566808	total: 3.16s	remaining: 5.29s
101:	learn: 2957.7209168	total: 3.23s	remaining: 5.31s
102:	learn: 2955.7692340	total: 3.26s	remaining: 5.28s
103:	learn: 2954.0690803	total: 3.29s	remaining: 5.25s
104:	learn: 2951.4953210	total: 3.35s	remaining: 5.26s
105:	learn: 2949.3378040	total: 3.4s	remaining: 5.26s
106:	learn: 2947.3234692	total: 3.43s	remaining: 5.22s
107:	learn: 2945.1412733	total: 3.45s	remaining: 5.17s
108:	learn: 2943.2595702	total: 3.47s	remaining: 5.13s
109:	learn: 2941.3142360	total: 3.5s	remaining: 5.09s
110:	learn: 2939.6177454	total: 3.53s	remaining: 5.06s
111:	learn: 2937.9208754	total: 3.57s	remaining: 5.04s
112:	learn: 2936.4503733	total: 3.64s	remaining: 5.06s
113:	learn: 2934.6425038	total: 3.67s	remaining: 5.03s
114:	learn: 2933.0333000	total: 3.72s	remaining: 5.01s
115:	learn: 2931.5612618	total: 3.77s	remaining: 5s
116:	learn: 2929.6967951	total: 3.81s	remaining: 4.98s
117:	learn: 2928.3735520	total: 3.83s	remaining: 4.93s
118:	learn: 2926.9676693	total: 3.85s	remaining: 4.89s
119:	learn: 2925.9405497	total: 3.88s	remaining: 4.85s
120:	learn: 2924.7526462	total: 3.95s	remaining: 4.87s
121:	learn: 2923.5226248	total: 3.99s	remaining: 4.84s
122:	learn: 2922.7398930	total: 4.01s	remaining: 4.79s
123:	learn: 2921.6695721	total: 4.04s	remaining: 4.76s
124:	learn: 2920.6999711	total: 4.08s	remaining: 4.73s
125:	learn: 2919.7380941	total: 4.13s	remaining: 4.71s
126:	learn: 2918.6023138	total: 4.17s	remaining: 4.69s
127:	learn: 2917.8321806	total: 4.22s	remaining: 4.68s
128:	learn: 2916.3227327	total: 4.24s	remaining: 4.64s
129:	learn: 2915.4067734	total: 4.26s	remaining: 4.59s
130:	learn: 2914.5466842	total: 4.27s	remaining: 4.53s
131:	learn: 2913.4304990	total: 4.3s	remaining: 4.5s
132:	learn: 2912.5042710	total: 4.38s	remaining: 4.51s
133:	learn: 2911.5213448	total: 4.42s	remaining: 4.48s
134:	learn: 2910.3882031	total: 4.45s	remaining: 4.45s
135:	learn: 2908.9354308	total: 4.47s	remaining: 4.41s
136:	learn: 2908.0790428	total: 4.5s	remaining: 4.37s
137:	learn: 2906.9522021	total: 4.52s	remaining: 4.32s
138:	learn: 2905.6537773	total: 4.55s	remaining: 4.29s
139:	learn: 2904.4121735	total: 4.58s	remaining: 4.26s
140:	learn: 2903.3498863	total: 4.63s	remaining: 4.24s
141:	learn: 2903.0661844	total: 4.64s	remaining: 4.19s
142:	learn: 2902.1924661	total: 4.68s	remaining: 4.16s
143:	learn: 2901.8800921	total: 4.71s	remaining: 4.12s
144:	learn: 2901.0908140	total: 4.75s	remaining: 4.09s
145:	learn: 2900.4241806	total: 4.76s	remaining: 4.04s
146:	learn: 2898.9655629	total: 4.82s	remaining: 4.03s
147:	learn: 2897.9251367	total: 4.86s	remaining: 4s
148:	learn: 2896.8560622	total: 4.89s	remaining: 3.97s
149:	learn: 2896.1636013	total: 4.91s	remaining: 3.93s
150:	learn: 2895.4210225	total: 4.93s	remaining: 3.89s
151:	learn: 2894.5131578	total: 4.96s	remaining: 3.85s
152:	learn: 2893.6820901	total: 4.99s	remaining: 3.81s

153:	learn: 2893.0456331	total: 5.05s	remaining: 3.81s
154:	learn: 2892.2198178	total: 5.1s	remaining: 3.78s
155:	learn: 2891.7271184	total: 5.13s	remaining: 3.75s
156:	learn: 2890.9268968	total: 5.17s	remaining: 3.72s
157:	learn: 2890.2698089	total: 5.21s	remaining: 3.69s
158:	learn: 2889.5453883	total: 5.23s	remaining: 3.65s
159:	learn: 2888.6956142	total: 5.28s	remaining: 3.63s
160:	learn: 2888.5154837	total: 5.32s	remaining: 3.6s
161:	learn: 2887.8605255	total: 5.35s	remaining: 3.56s
162:	learn: 2887.1467064	total: 5.36s	remaining: 3.52s
163:	learn: 2886.6209329	total: 5.4s	remaining: 3.49s
164:	learn: 2885.9708724	total: 5.42s	remaining: 3.45s
165:	learn: 2885.4932266	total: 5.47s	remaining: 3.43s
166:	learn: 2885.0688534	total: 5.5s	remaining: 3.39s
167:	learn: 2884.4738562	total: 5.52s	remaining: 3.35s
168:	learn: 2884.2389169	total: 5.55s	remaining: 3.32s
169:	learn: 2883.2243839	total: 5.58s	remaining: 3.28s
170:	learn: 2882.5985093	total: 5.61s	remaining: 3.25s
171:	learn: 2882.0093470	total: 5.66s	remaining: 3.23s
172:	learn: 2881.5112262	total: 5.69s	remaining: 3.19s
173:	learn: 2880.5647006	total: 5.73s	remaining: 3.16s
174:	learn: 2880.0069710	total: 5.76s	remaining: 3.13s
175:	learn: 2879.6848904	total: 5.79s	remaining: 3.09s
176:	learn: 2879.3267750	total: 5.83s	remaining: 3.06s
177:	learn: 2878.6147060	total: 5.86s	remaining: 3.03s
178:	learn: 2878.3942976	total: 5.88s	remaining: 2.99s
179:	learn: 2877.9872199	total: 5.91s	remaining: 2.96s
180:	learn: 2877.8609359	total: 5.93s	remaining: 2.92s
181:	learn: 2877.0516460	total: 5.96s	remaining: 2.88s
182:	learn: 2876.8579675	total: 5.99s	remaining: 2.85s
183:	learn: 2876.5283147	total: 6.03s	remaining: 2.82s
184:	learn: 2876.0418939	total: 6.06s	remaining: 2.78s
185:	learn: 2875.6254344	total: 6.09s	remaining: 2.75s
186:	learn: 2875.1524787	total: 6.12s	remaining: 2.72s
187:	learn: 2874.4977854	total: 6.15s	remaining: 2.68s
188:	learn: 2873.8139293	total: 6.22s	remaining: 2.67s
189:	learn: 2873.3660438	total: 6.29s	remaining: 2.65s
190:	learn: 2872.3137377	total: 6.31s	remaining: 2.61s
191:	learn: 2872.0643545	total: 6.34s	remaining: 2.57s
192:	learn: 2871.1987098	total: 6.37s	remaining: 2.54s
193:	learn: 2871.1896817	total: 6.38s	remaining: 2.5s
194:	learn: 2870.8081652	total: 6.42s	remaining: 2.47s
195:	learn: 2870.4088899	total: 6.46s	remaining: 2.44s
196:	learn: 2870.0534106	total: 6.48s	remaining: 2.4s
197:	learn: 2869.5478454	total: 6.51s	remaining: 2.37s
198:	learn: 2869.0963313	total: 6.54s	remaining: 2.33s
199:	learn: 2868.9552886	total: 6.58s	remaining: 2.3s
200:	learn: 2868.5798670	total: 6.61s	remaining: 2.27s
201:	learn: 2868.3700535	total: 6.66s	remaining: 2.24s
202:	learn: 2867.7593391	total: 6.69s	remaining: 2.21s
203:	learn: 2867.6022089	total: 6.72s	remaining: 2.17s
204:	learn: 2867.1006728	total: 6.76s	remaining: 2.14s
205:	learn: 2867.0856923	total: 6.77s	remaining: 2.1s
206:	learn: 2866.6701883	total: 6.8s	remaining: 2.07s
207:	learn: 2866.2491117	total: 6.85s	remaining: 2.04s
208:	learn: 2865.8221625	total: 6.88s	remaining: 2.01s
209:	learn: 2865.7495434	total: 6.91s	remaining: 1.97s
210:	learn: 2865.6107574	total: 6.94s	remaining: 1.94s
211:	learn: 2865.5965804	total: 6.95s	remaining: 1.9s
212:	learn: 2865.2571637	total: 6.98s	remaining: 1.87s
213:	learn: 2864.9760118	total: 7.02s	remaining: 1.84s
214:	learn: 2864.4970113	total: 7.04s	remaining: 1.8s
215:	learn: 2864.4680948	total: 7.05s	remaining: 1.76s
216:	learn: 2864.2965507	total: 7.06s	remaining: 1.73s
217:	learn: 2863.9069087	total: 7.1s	remaining: 1.69s
218:	learn: 2863.3952501	total: 7.13s	remaining: 1.66s
219:	learn: 2862.5554990	total: 7.16s	remaining: 1.63s
220:	learn: 2862.3275070	total: 7.21s	remaining: 1.6s
221:	learn: 2862.0161278	total: 7.25s	remaining: 1.57s
222:	learn: 2861.9237726	total: 7.27s	remaining: 1.53s
223:	learn: 2861.4685522	total: 7.31s	remaining: 1.5s
224:	learn: 2860.8161341	total: 7.34s	remaining: 1.47s
225:	learn: 2860.4147857	total: 7.39s	remaining: 1.44s
226:	learn: 2860.3219235	total: 7.41s	remaining: 1.4s
227:	learn: 2860.2512827	total: 7.44s	remaining: 1.37s
228:	learn: 2859.9558670	total: 7.46s	remaining: 1.34s
229:	learn: 2859.9111248	total: 7.48s	remaining: 1.3s
230:	learn: 2859.5058085	total: 7.5s	remaining: 1.27s
231:	learn: 2859.1397171	total: 7.54s	remaining: 1.23s
232:	learn: 2858.8696505	total: 7.55s	remaining: 1.2s
233:	learn: 2858.8685696	total: 7.62s	remaining: 1.17s
234:	learn: 2858.6651314	total: 7.66s	remaining: 1.14s
235:	learn: 2858.5852459	total: 7.67s	remaining: 1.1s
236:	learn: 2858.4485490	total: 7.69s	remaining: 1.07s
237:	learn: 2858.1131388	total: 7.72s	remaining: 1.04s
238:	learn: 2857.7280707	total: 7.77s	remaining: 1.01s
239:	learn: 2857.5323789	total: 7.79s	remaining: 974ms
240:	learn: 2857.1798899	total: 7.81s	remaining: 940ms
241:	learn: 2856.6886697	total: 7.83s	remaining: 907ms
242:	learn: 2856.3932961	total: 7.86s	remaining: 873ms
243:	learn: 2856.3648728	total: 7.87s	remaining: 839ms
244:	learn: 2856.2130565	total: 7.9s	remaining: 806ms
245:	learn: 2855.8049908	total: 7.93s	remaining: 774ms
246:	learn: 2855.4706631	total: 7.98s	remaining: 744ms
247:	learn: 2855.1489510	total: 8.01s	remaining: 710ms
248:	learn: 2854.7826451	total: 8.04s	remaining: 678ms
249:	learn: 2854.4701396	total: 8.08s	remaining: 646ms
250:	learn: 2854.2070385	total: 8.11s	remaining: 614ms
251:	learn: 2853.3603198	total: 8.15s	remaining: 582ms
252:	learn: 2853.3281379	total: 8.18s	remaining: 550ms
253:	learn: 2853.0063360	total: 8.22s	remaining: 518ms
254:	learn: 2852.5947748	total: 8.24s	remaining: 485ms
255:	learn: 2852.4719106	total: 8.29s	remaining: 454ms
256:	learn: 2852.0083460	total: 8.35s	remaining: 422ms
257:	learn: 2851.5565598	total: 8.37s	remaining: 389ms
258:	learn: 2851.3602274	total: 8.4s	remaining: 357ms
259:	learn: 2851.1096439	total: 8.43s	remaining: 324ms
260:	learn: 2850.9169887	total: 8.45s	remaining: 291ms
261:	learn: 2850.9110137	total: 8.46s	remaining: 258ms
262:	learn: 2850.6024895	total: 8.48s	remaining: 226ms
263:	learn: 2850.4862471	total: 8.51s	remaining: 193ms
264:	learn: 2850.0961279	total: 8.56s	remaining: 161ms
265:	learn: 2849.8158947	total: 8.59s	remaining: 129ms
266:	learn: 2849.4304697	total: 8.61s	remaining: 96.7ms
267:	learn: 2849.4284999	total: 8.62s	remaining: 64.3ms
268:	learn: 2849.2709767	total: 8.63s	remaining: 32.1ms
269:	learn: 2848.7171752	total: 8.66s	remaining: 0us

In [104]:
coeff_score = ctb.score(X_test,y_test)
coeff_score

0.5753424452803774

In [33]:
# ctb.score(X_train,y_train)

# predicting the test data

In [34]:
X2=df2.drop(['Product_Identifier','Product_Supermarket_Identifier','Product_Weight',
           'Supermarket_Opening_Year','Product_Supermarket_Sales'], axis=1)
X2.head()

KeyError: "['Product_Supermarket_Sales'] not found in axis"

In [ ]:
priiii()

In [ ]:
test_pred = ctb.predict(X2) #predict on the test set for submission
df3= {'Product_Supermarket_Identifier': df2['Product_Supermarket_Identifier'], 'Product_Supermarket_Sales': test_pred}
sub = pd.DataFrame(data=df3)
sub = sub[['Product_Supermarket_Identifier', 'Product_Supermarket_Sales']]

sub.to_csv('submission_recent4.csv', index = False)
sub.head()

Croos validation